
spring:
  application:
    name: gateway

  security:
    oauth2:
      jwt:
        signingKey: 123456

  cloud:
    nacos:
      discovery:
        server-addr: 36.133.231.227:8848
    gateway:
      routes:
        - id: userservice
          uri: lb://userservice
          predicates:
            - Path=/user/**
        - id: indexservice
          uri: lb://indexservice
          predicates:
            - Path=/index/**
server:
  port: 10010