server:
  port: 8084

spring:
  application:
    name: securityservice
  cloud:
    nacos:
      discovery:
        server-addr: 43.143.208.20:8848
  redis:
    host: 43.143.208.20
    port: 6379
    timeout: 3000
    lettuce:
      pool:
        max-active: -1
        max-wait: -1s
        max-idle: 50
        min-idle: 10
    database: 0
    password: ''

  datasource:
    url: jdbc:mysql://43.143.208.20:3306/age_user?serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver