server:
  port: 8082

spring:
  application:
    name: musicservice

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://36.133.231.227:3306/tp_music?serverTimezone=GMT%2B8
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 36.133.231.227:8848